# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  PTE_config = debug
endif
ifeq ($(config),release)
  PTE_config = release
endif

PROJECTS := PTE

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

PTE:
ifneq (,$(PTE_config))
	@echo "==== Building PTE ($(PTE_config)) ===="
	@${MAKE} --no-print-directory -C . -f PTE.make config=$(PTE_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f PTE.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   PTE"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"